/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c QWCtlAdaptor -a qwctl_adaptor se.liu.lysator.qwctl.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef QWCTL_ADAPTOR_H_1278976819
#define QWCTL_ADAPTOR_H_1278976819

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
class QApplication;

/*
 * Adaptor class for interface se.liu.lysator.qwctl
 */
class QWCtlAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "se.liu.lysator.qwctl")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"se.liu.lysator.qwctl\">\n"
"    <!-- Properties, i.e. data carrying variables -->\n"
"    <property access=\"readwrite\" type=\"s\" name=\"name\"/>\n"
"    <!-- Methods, or slots which receives information -->\n"
"    <method name=\"setPosition\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"x\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"y\"/>\n"
"    </method>\n"
"    <method name=\"setSize\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"x\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"y\"/>\n"
"    </method>\n"
"    <method name=\"setMinimized\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"minimize\"/>\n"
"    </method>\n"
"    <!-- Signals, i.e. emitted information -->\n"
"    <signal name=\"applicationInfo\">\n"
"      <annotation value=\"QVariant\" name=\"com.trolltech.QtDBus.QtTypeName.In0\"/>\n"
"      <arg type=\"a{sv}\" name=\"info\"/>\n"
"    </signal>\n"
"    <signal name=\"applicationClosed\"/>\n"
"  </interface>\n"
        "")

 public:
  QWCtlAdaptor(QObject *parent);
  virtual ~QWCtlAdaptor();

 public: // PROPERTIES
  Q_PROPERTY(QString name READ name WRITE setName)
  QString name() const;
  void setName(const QString &value);

 public Q_SLOTS: // METHODS
  void setMinimized(bool minimize);
  void setPosition(int x, int y);
  void setSize(int x, int y);

 Q_SIGNALS: // SIGNALS
  void applicationClosed();
  void applicationInfo(const QVariant &info);
};

#endif
